### ISSUE TITLE
ローカルのデータをデータベースサーバに移行してデータを取得できるようにする。

### ISSUE THREAD

**Issue by kiko1401839** [kiko1401839/ramen-review-app#3]

**Comment by kiko1401839** [comment]
dockerでpostgreSQLを起動する
```
docker run -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=review_app -p 5432:5432 postgres:12
```

**Comment by kiko1401839** [comment]
herokuにAPIサーバをデプロイしたが、APIが正しく動作していない。

**Comment by kiko1401839** [comment]
```
heroku logs --tail
2021-07-31T07:15:07.818054+00:00 app[web.1]: at addChunk (internal/streams/readable.js:290:12)
2021-07-31T07:15:07.818054+00:00 app[web.1]: at readableAddChunk (internal/streams/readable.js:265:9)
2021-07-31T07:15:07.818054+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-07-31T07:15:07.818150+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-07-31T07:15:07.818251+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-07-31T07:15:11.770749+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: SequelizeConnectionError: no pg_hba.conf entry for host "34.239.187.247", user "wfhnmadkyitncn", database "devkl48hioei5o", SSL off
2021-07-31T07:15:11.770759+00:00 app[web.1]: at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)
2021-07-31T07:15:11.770760+00:00 app[web.1]: at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)
2021-07-31T07:15:11.770761+00:00 app[web.1]: at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:325:19)
2021-07-31T07:15:11.770762+00:00 app[web.1]: at Connection.emit (events.js:400:28)
2021-07-31T07:15:11.770763+00:00 app[web.1]: at /app/node_modules/pg/lib/connection.js:114:12
2021-07-31T07:15:11.770763+00:00 app[web.1]: at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
2021-07-31T07:15:11.770764+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
2021-07-31T07:15:11.770764+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-07-31T07:15:11.770765+00:00 app[web.1]: at addChunk (internal/streams/readable.js:290:12)
2021-07-31T07:15:11.770765+00:00 app[web.1]: at readableAddChunk (internal/streams/readable.js:265:9)
2021-07-31T07:15:11.770822+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2021-07-31T07:15:37.750446+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/restaurants" host=nameless-plateau-20423.herokuapp.com request_id=e28ab53b-9c08-4c48-a57f-97cde8290bf2 fwd="219.99.238.87" dyno=web.1 connect=1ms service=30004ms status=503 bytes=0 protocol=https
2021-07-31T07:15:41.755233+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/restaurants" host=nameless-plateau-20423.herokuapp.com request_id=bd99507e-195d-4f18-aa04-b3d8884ee158 fwd="219.99.238.87" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
2021-07-31T07:17:04.462444+00:00 app[api]: Running release v8 commands by user kyamasaki95624@gmail.com
2021-07-31T07:17:04.462444+00:00 app[api]: Attach HEROKU_POSTGRESQL_ORANGE (@ref:postgresql-symmetrical-38077) by user kyamasaki95624@gmail.com
2021-07-31T07:17:04.473459+00:00 app[api]: Release v9 created by user kyamasaki95624@gmail.com
2021-07-31T07:17:04.473459+00:00 app[api]: @ref:postgresql-symmetrical-38077 completed provisioning, setting HEROKU_POSTGRESQL_ORANGE_URL. by user kyamasaki95624@gmail.com
2021-07-31T07:17:04.705864+00:00 heroku[web.1]: Restarting
2021-07-31T07:17:04.726588+00:00 heroku[web.1]: State changed from up to starting
2021-07-31T07:17:05.802720+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-07-31T07:17:05.948934+00:00 heroku[web.1]: Process exited with status 143
2021-07-31T07:17:08.308593+00:00 heroku[web.1]: Starting process with command `node index.js`
2021-07-31T07:17:11.611074+00:00 app[web.1]: Listening at http://localhost:47991
2021-07-31T07:17:12.693650+00:00 heroku[web.1]: State changed from starting to up
2021-07-31T07:29:17.030150+00:00 heroku[router]: at=info method=GET path="/" host=nameless-plateau-20423.herokuapp.com request_id=038b1be5-99cc-4662-802d-9d2a93d86eec fwd="219.99.238.87" dyno=web.1 connect=0ms service=17ms status=404 bytes=415 protocol=https
2021-07-31T07:29:26.603192+00:00 heroku[router]: at=info method=GET path="//restaurants" host=nameless-plateau-20423.herokuapp.com request_id=078ed055-5b12-40c4-a03c-8620cff18dce fwd="219.99.238.87" dyno=web.1 connect=0ms service=3ms status=404 bytes=427 protocol=https
2021-07-31T07:29:32.763958+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: SequelizeConnectionError: no pg_hba.conf entry for host "34.203.30.151", user "wfhnmadkyitncn", database "devkl48hioei5o", SSL off
2021-07-31T07:29:32.763969+00:00 app[web.1]: at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)
2021-07-31T07:29:32.763970+00:00 app[web.1]: at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)
2021-07-31T07:29:32.763971+00:00 app[web.1]: at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:325:19)
2021-07-31T07:29:32.763972+00:00 app[web.1]: at Connection.emit (events.js:400:28)
2021-07-31T07:29:32.763973+00:00 app[web.1]: at /app/node_modules/pg/lib/connection.js:114:12
2021-07-31T07:29:32.763974+00:00 app[web.1]: at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
2021-07-31T07:29:32.763974+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
2021-07-31T07:29:32.763974+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-07-31T07:29:32.763975+00:00 app[web.1]: at addChunk (internal/streams/readable.js:290:12)
2021-07-31T07:29:32.763975+00:00 app[web.1]: at readableAddChunk (internal/streams/readable.js:265:9)
2021-07-31T07:29:32.763976+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-07-31T07:29:32.764098+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-07-31T07:29:32.764217+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-07-31T07:29:36.723144+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: SequelizeConnectionError: no pg_hba.conf entry for host "34.203.30.151", user "wfhnmadkyitncn", database "devkl48hioei5o", SSL off
2021-07-31T07:29:36.723159+00:00 app[web.1]: at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)
2021-07-31T07:29:36.723160+00:00 app[web.1]: at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)
2021-07-31T07:29:36.723161+00:00 app[web.1]: at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:325:19)
2021-07-31T07:29:36.723162+00:00 app[web.1]: at Connection.emit (events.js:400:28)
2021-07-31T07:29:36.723163+00:00 app[web.1]: at /app/node_modules/pg/lib/connection.js:114:12
2021-07-31T07:29:36.723163+00:00 app[web.1]: at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
2021-07-31T07:29:36.723164+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
2021-07-31T07:29:36.723164+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-07-31T07:29:36.723164+00:00 app[web.1]: at addChunk (internal/streams/readable.js:290:12)
2021-07-31T07:29:36.723165+00:00 app[web.1]: at readableAddChunk (internal/streams/readable.js:265:9)
2021-07-31T07:29:36.723231+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2021-07-31T07:30:02.714998+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/restaurants" host=nameless-plateau-20423.herokuapp.com request_id=10ebeb72-234c-43bd-b3e0-0d79b020b6dd fwd="219.99.238.87" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
2021-07-31T07:30:06.697794+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/restaurants" host=nameless-plateau-20423.herokuapp.com request_id=8d8a0926-6e8b-4466-a270-132577fc2d55 fwd="219.99.238.87" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0 protocol=https
2021-07-31T07:40:26.000000+00:00 app[api]: Build started by user kyamasaki95624@gmail.com
2021-07-31T07:40:50.785778+00:00 app[api]: Deploy ea1a5e15 by user kyamasaki95624@gmail.com
2021-07-31T07:40:50.785778+00:00 app[api]: Release v10 created by user kyamasaki95624@gmail.com
2021-07-31T07:40:51.000000+00:00 app[api]: Build succeeded
2021-07-31T07:40:54.038917+00:00 heroku[web.1]: Restarting
2021-07-31T07:40:54.041430+00:00 heroku[web.1]: State changed from up to starting
2021-07-31T07:40:54.921196+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-07-31T07:40:54.995945+00:00 heroku[web.1]: Process exited with status 143
2021-07-31T07:40:57.155735+00:00 heroku[web.1]: Starting process with command `node index.js`
2021-07-31T07:41:00.718849+00:00 app[web.1]: Listening at http://localhost:56462
2021-07-31T07:41:01.519417+00:00 heroku[web.1]: State changed from starting to up
2021-07-31T07:50:59.899323+00:00 heroku[router]: at=info method=GET path="/" host=nameless-plateau-20423.herokuapp.com request_id=36bf3260-c3c3-4152-a351-1203ed3519f8 fwd="219.99.238.87" dyno=web.1 connect=1ms service=42ms status=404 bytes=415 protocol=https
2021-07-31T07:51:06.750283+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: SequelizeConnectionError: no pg_hba.conf entry for host "54.224.96.134", user "wfhnmadkyitncn", database "devkl48hioei5o", SSL off
2021-07-31T07:51:06.750302+00:00 app[web.1]: at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)
2021-07-31T07:51:06.750304+00:00 app[web.1]: at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)
2021-07-31T07:51:06.750305+00:00 app[web.1]: at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:325:19)
2021-07-31T07:51:06.750306+00:00 app[web.1]: at Connection.emit (events.js:400:28)
2021-07-31T07:51:06.750306+00:00 app[web.1]: at /app/node_modules/pg/lib/connection.js:114:12
2021-07-31T07:51:06.750307+00:00 app[web.1]: at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
2021-07-31T07:51:06.750307+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
2021-07-31T07:51:06.750307+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-07-31T07:51:06.750308+00:00 app[web.1]: at addChunk (internal/streams/readable.js:290:12)
2021-07-31T07:51:06.750308+00:00 app[web.1]: at readableAddChunk (internal/streams/readable.js:265:9)
2021-07-31T07:51:06.750309+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-07-31T07:51:06.750379+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-07-31T07:51:06.750459+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-07-31T07:51:10.680153+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: SequelizeConnectionError: no pg_hba.conf entry for host "54.224.96.134", user "wfhnmadkyitncn", database "devkl48hioei5o", SSL off
2021-07-31T07:51:10.680168+00:00 app[web.1]: at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)
2021-07-31T07:51:10.680178+00:00 app[web.1]: at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)
2021-07-31T07:51:10.680180+00:00 app[web.1]: at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:325:19)
2021-07-31T07:51:10.680181+00:00 app[web.1]: at Connection.emit (events.js:400:28)
2021-07-31T07:51:10.680182+00:00 app[web.1]: at /app/node_modules/pg/lib/connection.js:114:12
2021-07-31T07:51:10.680183+00:00 app[web.1]: at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
2021-07-31T07:51:10.680183+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
2021-07-31T07:51:10.680183+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-07-31T07:51:10.680184+00:00 app[web.1]: at addChunk (internal/streams/readable.js:290:12)
2021-07-31T07:51:10.680184+00:00 app[web.1]: at readableAddChunk (internal/streams/readable.js:265:9)
2021-07-31T07:51:10.680219+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2021-07-31T07:51:36.670655+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/restaurants" host=nameless-plateau-20423.herokuapp.com request_id=521ae7a3-af41-4a07-82e0-0a966241ab6f fwd="219.99.238.87" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https
2021-07-31T07:51:40.676319+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/restaurants" host=nameless-plateau-20423.herokuapp.com request_id=a39770db-c20e-4ff7-aa86-679c5663061c fwd="219.99.238.87" dyno=web.1 connect=0ms service=30004ms status=503 bytes=0 protocol=https
2021-07-31T07:55:09.385463+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: SequelizeConnectionError: no pg_hba.conf entry for host "54.224.96.134", user "wfhnmadkyitncn", database "devkl48hioei5o", SSL off
2021-07-31T07:55:09.385474+00:00 app[web.1]: at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)
2021-07-31T07:55:09.385476+00:00 app[web.1]: at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)
2021-07-31T07:55:09.385480+00:00 app[web.1]: at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:325:19)
2021-07-31T07:55:09.385481+00:00 app[web.1]: at Connection.emit (events.js:400:28)
2021-07-31T07:55:09.385482+00:00 app[web.1]: at /app/node_modules/pg/lib/connection.js:114:12
2021-07-31T07:55:09.385483+00:00 app[web.1]: at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
2021-07-31T07:55:09.385483+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
2021-07-31T07:55:09.385484+00:00 app[web.1]: at Socket.emit (events.js:400:28)
2021-07-31T07:55:09.385484+00:00 app[web.1]: at addChunk (internal/streams/readable.js:290:12)
2021-07-31T07:55:09.385484+00:00 app[web.1]: at readableAddChunk (internal/streams/readable.js:265:9)
2021-07-31T07:55:09.385552+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
2021-07-31T07:55:39.374050+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/restaurants" host=nameless-plateau-20423.herokuapp.com request_id=c6d27ea6-fe3c-4e68-95a7-b7838305ad4f fwd="219.99.238.87" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
```

**Comment by kiko1401839** [comment]
問題の切り分け

- [ ] Heroku上でAPIサーバの起動
- [ ] DBのmigration
- [ ] APIサーバからDBへのアクセス
- [ ] ブラウザからAPIサーバへのリクエスト
- [ ] APIサーバからブラウザへのレスポンス

**Comment by kiko1401839** [comment]
Heroku上のAPIサーバからPostgreSQLにアクセスするときはSSLじゃないとだめぽい

**Comment by kiko1401839** [comment]
pgのバージョンが変わって以下のように設定してあげないといけない
```
export const sequelize = new Sequelize(url, {
  dialectOptions: {
    ssl: {
      require: true,
      rejectUnauthorized: false,
    },
  },
});
```
